apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "resource-to-claim-mutating-webhook.example.com"
webhooks:
  - name: "resource-to-claim-mutating-webhook.example.com"
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: "nrt-to-dra"
        name: "resource-to-claim-mutating-webhook-service"
        path: "/mutate"
      caBundle: CA_BUNDLE
    failurePolicy: Fail
    sideEffects: NoneOnDryRun
    timeoutSeconds: 5
    admissionReviewVersions: ["v1"]
    matchConditions:
      - expression: 'object.spec.schedulerName == "topology-aware"'
        name: 'match-tas-scheduling-pods'